# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

development_sec:
  adapter: mysql2
  database: <%= ENV['MYSQL_DATABASE'] %>
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: <%= ENV['SERVER_NAME_OR_IP'] %>
  port: <%= ENV['MYSQL_PORT'] %>

development_csgo:
  adapter: mysql2
  database: <%= ENV['MYSQL_DATABASE'] %>
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: <%= ENV['SERVER_NAME_OR_IP'] %>
  port: <%= ENV['MYSQL_PORT'] %>
