development:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['POSTGRESQL_NAME'] %>
  username: <%= ENV['POSTGRESQL_USER'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
  port: <%= ENV['POSTGRESQL_PORT'] || '5432' %>
  host: <%= ENV['POSTGRESQL_HOST'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development_sec:
  adapter: mysql2
  database: <%= ENV['MYSQL_DATABASE'] %>
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: <%= ENV['SERVER_NAME_OR_IP'] %>
  port: <%= ENV['MYSQL_PORT'] %>

development_csgo:
  adapter: mysql2
  database: <%= ENV['MYSQL_DATABASE'] %>
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: <%= ENV['SERVER_NAME_OR_IP'] %>
  port: <%= ENV['MYSQL_PORT'] %>
