class CreateRankmeCsgo < ActiveRecord::Migration[5.0]
  def change
    create_table :rankme_csgos do |t|
      t.string :steam
    	t.string :name
    	t.string :lastip
    	t.integer :score
    	t.integer :kills
    	t.integer :deaths
      t.integer :assists
    	t.integer :suicides
    	t.integer :tk
    	t.integer :shots
    	t.integer :hits
    	t.integer :headshots
    	t.integer :connected
    	t.integer :rounds_tr
    	t.integer :rounds_ct
    	t.integer :lastconnect
    	t.integer :knife
    	t.integer :glock
      t.integer :hkp2000
    	t.integer :usp_silencer
    	t.integer :p250
    	t.integer :deagle
    	t.integer :elite
    	t.integer :fiveseven
      t.integer :tec9
      t.integer :cz75a
      t.integer :revolver
    	t.integer :nova
    	t.integer :xm1014
      t.integer :mag7
      t.integer :sawedoff
      t.integer :bizon
    	t.integer :mac10
    	t.integer :mp9
      t.integer :mp7
    	t.integer :ump45
    	t.integer :p90
    	t.integer :galilar
    	t.integer :ak47
    	t.integer :scar20
    	t.integer :famas
    	t.integer :m4a1
      t.integer :m4a1_silencer
    	t.integer :aug
      t.integer :ssg08
      t.integer :sg556
    	t.integer :awp
    	t.integer :g3sg1
    	t.integer :m249
      t.integer :negev
    	t.integer :hegrenade
    	t.integer :flashbang
    	t.integer :smokegrenade
      t.integer :inferno
      t.integer :decoy
      t.integer :taser
    	t.integer :head
    	t.integer :chest
    	t.integer :stomach
    	t.integer :left_arm
    	t.integer :right_arm
    	t.integer :left_leg
    	t.integer :right_leg
    	t.integer :c4_planted
    	t.integer :c4_exploded
    	t.integer :c4_defused
    	t.integer :ct_win
    	t.integer :tr_win
    	t.integer :hostages_rescued
    	t.integer :vip_killed
    	t.integer :vip_escaped
    	t.integer :vip_played
      t.integer :mvp
      t.integer :damage
      t.integer :user_id
      t.integer :map_id
      t.integer :tournament_id
      t.timestamps
    end
  end
end
