class Weapon
  IMAGE = HashWithIndifferentAccess.new(
    'USP-S': 'weapon_usp_silencer.svg',
    'M4A1': 'weapon_m4a1_silencer.svg',
    'AK-47': 'weapon_ak47.svg',
    'MAC-10': 'weapon_mac10.svg',
    'Molotov': 'weapon_inferno.svg',
    'AWP': 'weapon_awp.svg',
    'Desert Eagle': 'weapon_deagle.svg',
    'Galil AR': 'weapon_galilar.svg',
    'Knife': 'weapon_knife.svg',
    'MP9': 'weapon_mp9.svg',
    'FAMAS': 'weapon_famas.svg',
    'Glock-18': 'weapon_glock.svg',
    'MAG-7': 'weapon_mag7.svg',
    'Five-SeveN': 'weapon_fiveseven.svg',
    'M4A4': 'weapon_m4a1.svg',
    'Tec-9': 'weapon_tec9.svg',
    'UMP-45': 'weapon_ump45.svg',
    'Zeus x27': 'weapon_taser.svg',
    'AUG': 'weapon_aug.svg',
    'Incendiary Grenade': 'weapon_incgrenade.svg',
    'SCAR-20': 'weapon_scar20.svg',
    'Dual Berettas': 'weapon_elite.svg',
    'SSG 08': 'weapon_ssg08.svg',
    'XM1014': 'weapon_xm1014.svg',
    'Negev': 'weapon_negev.svg',
    'P250': 'weapon_p250.svg',
    'Nova': 'weapon_nova.svg',
  )
end
